---
title: "E-Book Subject Analysis"
output: github_document
always_allow_html: true
---

```{r message = FALSE}
# load libraries
library(tidyverse)
library(formattable)
library(kableExtra)
```

```{r}
# import combine usage file
tr_books <- read_csv("usage_data.csv", show_col_types = FALSE)
```

## Unique ISBNs

```{r}
# calculate number of missing isbns
count_missing_isbn <- sum(is.na(tr_books$isbn))
print(count_missing_isbn)

# calculate proportion of missing isbns
item_count <- nrow(tr_books)
prop_missing_isbn <- count_missing_isbn / item_count
print(percent(prop_missing_isbn))

# create list of unique isbns
tr_books <- tr_books %>%
  mutate(isbn_norm = str_remove_all(isbn, "-"))

unique_isbn <- tr_books %>%
  select(isbn_norm) %>%
  distinct(isbn_norm)

# calculate number of unique isbns and print output
count_unique_isbn <- n_distinct(unique_isbn)
print(count_unique_isbn)

# output cvs file with unique isbns
write_csv(unique_isbn, "unique_isbn.csv")
```

## Summary Statistics

```{r}
# calculate titles and usage by access type
tr_books_usage <- tr_books %>%
  filter(metric == "Unique Title Requests")

item_count_usage = nrow(tr_books_usage)
unique_title_requests = sum(tr_books_usage$total)

tr_books_usage %>%
  group_by(access_type) %>%
  summarize(titles = n(), pct_titles = percent(n()/item_count_usage),
            usage = sum(total), pct_usage = percent(sum(total)/unique_title_requests)) %>%
  kbl() %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

```


